[project]
name = "credit-risk-es"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "basedpyright>=1.32.1",
    "kaggle>=1.7.4.5",
    "marimo>=0.17.2",
    "python-lsp-server>=1.13.1",
    "ty>=0.0.1a24",
]
